Update dockerfile_stage3
cardano-community/guild-operators pull request #1173
Opened 2021-11-03 04:39 UTC by redoracle

docker improvements

2021-11-03 06:13 UTC, TrevorBenson requested changes
LGTM except the cncli alias.

2021-11-03 06:13 UTC, TrevorBenson commented on files/docker/node/dockerfile_stage3
> +    && echo "alias cnclis=$CNODE_HOME/scripts/cncli.sh" >> ~/.bashrc \
```suggestion
    && echo "alias cncli=$CNODE_HOME/scripts/cncli.sh" >> ~/.bashrc \
```

2021-11-03 06:22 UTC, TrevorBenson approved these changes

2021-11-03 06:24 UTC, merged

2021-11-04 13:51 UTC, redoracle commented
> LGTM except the cncli alias.

Why you didn't fix before merging?

2021-11-06 23:04 UTC, TrevorBenson commented
Strange, I had suggested a change to fix the s, and I clicked confirm on it
before I chose to merge. I presumed it was committed and included.

On Thu, Nov 4, 2021 at 6:52 AM Michael ***@***.***> wrote:

> LGTM except the cncli alias.
>
> Why you didn't fix before merging?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cardano-community/guild-operators/pull/1173#issuecomment-960975899>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACF6ID3LOPZCSQXYVQSSXNDUKKFYHANCNFSM5HIAF56A>
> .
>