Improve various queries and add new credential_txs
cardano-community/guild-operators pull request #1205
Opened 2021-11-29 16:02 UTC by Scitz0

credential_txs similar to address_txs but takes payment credential array as input instead

2021-11-29 22:00 UTC, Scitz0 commented on files/grest/rpc/pool/pool_info.sql
> +      SUM (es.amount)::lovelace AS as_sum
👍  updated

2021-11-29 22:01 UTC, DamjanOstrelic approved these changes

2021-11-30 20:06 UTC, DamjanOstrelic requested changes

2021-11-30 20:06 UTC, DamjanOstrelic commented on files/grest/rpc/pool/pool_info.sql
> +      easc.pool_id = pic.pool_id_bech32
```suggestion
      easc.pool_id = pic.pool_id_bech32 AND
      easc.epoch_no = _epoch_no
```

2021-11-30 20:06 UTC, DamjanOstrelic commented on files/grest/rpc/pool/pool_info.sql
> +      easc.pool_id = pic.pool_id_bech32
The cache table has an entry for every epoch, here we only want to look at the current epoch.

2021-12-01 03:51 UTC, rdlrt approved these changes

2021-12-01 10:12 UTC, merged