Doc updates #3
cardano-community/guild-operators pull request #961
Opened 2021-06-19 08:08 UTC by DamjanOstrelic

- gLiveView
- ITN stuff
- topologyUpdater

Probably good idea for @Scitz0 and @gufmar to take a look and confirm I think.

2021-06-19 10:07 UTC, Scitz0 requested changes

2021-06-19 14:57 UTC, DamjanOstrelic commented on docs/Scripts/gliveview.md
> +To get current epoch blocks, the [cntoolsBlockCollector.sh](Scripts/logmonitor.md) script is needed. This is optional and **Guild LiveView** will function without it.
Yep, good catch, fixed the link but not the title :)

2021-06-19 16:35 UTC, DamjanOstrelic commented on docs/Scripts/gliveview.md
> +NO_INTERNET_MODE="N"                       # To skip checking for auto updates or make outgoing connections to guild-operators github repository
I pushed some new changes now, some questions:

1) Does `logMonitor.sh` have user variables?
2) Separate page for `cnode.sh`? Right now, I just added info on the `node-cli.md`
3) What about `cntools.config`? Separate page? Or should it belong in the CNTools page, maybe somewhere close to where it is first mentioned? Along with CNCLI, this is the only thing with user variables that I still have to check / change.

2021-06-21 08:38 UTC, gufmar approved these changes
LGTM

2021-06-21 10:05 UTC, Scitz0 approved these changes
👍

2021-06-21 10:11 UTC, Scitz0 commented on docs/Scripts/gliveview.md
> +NO_INTERNET_MODE="N"                       # To skip checking for auto updates or make outgoing connections to guild-operators github repository
> 1. Does `logMonitor.sh` have user variables?

No


> 2. Separate page for `cnode.sh`? Right now, I just added info on the `node-cli.md`

Not sure its needed, its a simple script to launch the node, not sure what to describe on separate page for it. But if you feel you can make a page of it, by all means go for it. 


> 3. What about `cntools.config`? Separate page? Or should it belong in the CNTools page, maybe somewhere close to where it is first mentioned? Along with CNCLI, this is the only thing with user variables that I still have to check / change.

I think it's enough to have a section on CNTools main page like for the other scripts, like cncli, called configuration. But make it clear that its a separate file for this script compared to rest.

2021-06-21 19:12 UTC, DamjanOstrelic commented on docs/Scripts/gliveview.md
> +NO_INTERNET_MODE="N"                       # To skip checking for auto updates or make outgoing connections to guild-operators github repository
@Scitz0, I was thinking about point 3) but the CNTools page currently offers good info on the file (not too much detail into its contents but clear about what it's used for and that it is a separate file. I think we can merge this for now as I am still going through the docs updating the existing pages. In the next PRs, I would add a separate page for it with examples on what the variables inside control.

2021-06-21 21:23 UTC, Scitz0 commented on docs/Scripts/gliveview.md
> +NO_INTERNET_MODE="N"                       # To skip checking for auto updates or make outgoing connections to guild-operators github repository
Ok thats fine with me.

2021-06-22 04:44 UTC, rdlrt approved these changes

2021-06-25 09:07 UTC, merged